### ISSUE TITLE
Is my AMD card? RX580 8GB

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [deroberon/StableZero123-comfyui#1]
FETCH DATA from: C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
text_encoder\model.safetensors not found
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 8/8 [00:17<00:00,  2.23s/it]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\custom_nodes\StableZero123-comfyui\stablezero123.py", line 103, in execute
    pipeline.to('cuda:0')
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 864, in to
    module.to(device, dtype)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\WarMachineV10SSD3\Music\ComfyPortable\ComfyUI_windows_portable\ComfyUI\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Prompt executed in 18.99 seconds

**Comment by deroberon** [comment]
Exactly. For now the implementation just supports CUDA and AMD cards uses ROCm, if I'm not wrong.

**Comment by KillyTheNetTerminal** [comment]
Ohh.. Okay, thanks for the information. There is a chance in the future to work with DirectML?

**Comment by deroberon** [comment]
In fact... I don't have an AMD card to try... but I was reading about pytorch and rocm and it seems that nowadays it is 100% compatible with cuda implementations. What makes me think if the problem you are facing isn't because you really have in your python env a version of pytorch that was not pre-compiled with cuda support as the error message says. 

How exactly did you install your version of comfyui? Are you running it in what OS? If you are not using the portable comfyui version, how do you install pytorch in your python env? And if you are using the portable version, how are you starting comfyui? with run_nvidia_gpu or run_cpu?

**Comment by NeedsMoar** [comment]
AMD on Windows still uses DirectML.  It's incompatible with CUDA / torch versions targeting CUDA and missing a lot of basic functionality (and speed).  I'm not sure if AMD has even released all of the libraries needed to build a custom build of pytorch rocm on Windows yet, and when they do it'll probably be months before there's an official torch build.    

DirectML is fundamentally useless in its current state when used from Python, anyway.  It can run ONNX models quickly but everything else has zero memory management and near-unusable speeds for image sizes above ~1024x1024.

**Comment by aviddv1** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
shubham-kaushal, @ukexim13, @manoloacademia, @zyl15735648281, @2EXP, @meaze0507, @Asim-Tahir, @KhalidAdan, @WUSO01, @avatarxy, @EricSKCheng, @athomik79, @ki1o, @robert-antofe, @developerasun, @jase-codebase, @arod12345, @jiajiayao, @marian2js, @ibrahimmusman2050, @dkillen, @singhs020, @TaeKKun, @MeizhaiTechnology, @iNorthIsle, @viper-00, @moifort, @dinuka-rp, @rscavone2, @RyotaBannai, @ahammed867, @philmaas, @EricDeColS, @super117893344p, @annahedstroem, @fipo, @YeShen-code, @fangedhex, @naltun, @GrisaiaEvy, @lazyman01, @3lang3, @SmartContract0421, @5k3105, @varunramesh26, @Yothgewalt, @hiro08gh, @mikeaxle, @Jiashuo-Zhang, @long-blade
